/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gradecalculator;
import javax.swing.JOptionPane;
/**
 *
 * @author THABANI.N
 */
public class studentgrade extends javax.swing.JFrame {

    /**
     * Creates new form studentgrade
     */
    public studentgrade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mStudent = new javax.swing.JLabel();
        StudentNumber = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        SubjectModules = new javax.swing.JLabel();
        English = new javax.swing.JLabel();
        Afrikaans = new javax.swing.JLabel();
        Mathematics = new javax.swing.JLabel();
        PhysicalSciences = new javax.swing.JLabel();
        cCalculate = new javax.swing.JButton();
        TotalMarks = new javax.swing.JLabel();
        Percentage = new javax.swing.JLabel();
        Grade = new javax.swing.JLabel();
        rReset = new javax.swing.JButton();
        sNumber = new javax.swing.JTextField();
        nName = new javax.swing.JTextField();
        eEnglish = new javax.swing.JTextField();
        aAfrikaans = new javax.swing.JTextField();
        mMaths = new javax.swing.JTextField();
        pSciences = new javax.swing.JTextField();
        tMarks = new javax.swing.JTextField();
        pPercentage = new javax.swing.JTextField();
        gGrade = new javax.swing.JTextField();
        RemarksL = new javax.swing.JTextField();
        Remarks = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mStudent.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        mStudent.setText("My Student Grade Calculator");

        StudentNumber.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        StudentNumber.setText("Student Number:");

        Name.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Name.setText("Name:");

        SubjectModules.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        SubjectModules.setText("Subjects/Modules:");

        English.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        English.setText("English:");

        Afrikaans.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Afrikaans.setText("Afrikaans:");

        Mathematics.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Mathematics.setText("Mathematics:");

        PhysicalSciences.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        PhysicalSciences.setText("Physical Sciences:");

        cCalculate.setBackground(new java.awt.Color(0, 255, 51));
        cCalculate.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cCalculate.setText("Calculate");
        cCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCalculateActionPerformed(evt);
            }
        });

        TotalMarks.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        TotalMarks.setText("Total Marks:");

        Percentage.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Percentage.setText("Percentage:");

        Grade.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Grade.setText("Grade:");

        rReset.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        rReset.setText("Reset");
        rReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rResetActionPerformed(evt);
            }
        });

        nName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nNameActionPerformed(evt);
            }
        });

        Remarks.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Remarks.setText("Remarks:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 23, Short.MAX_VALUE)
                        .addComponent(mStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudentNumber)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(PhysicalSciences, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SubjectModules, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Percentage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TotalMarks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                        .addComponent(nName)
                                        .addComponent(pPercentage, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                        .addComponent(tMarks))
                                    .addComponent(cCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pSciences, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(English)
                                    .addGap(121, 121, 121)
                                    .addComponent(eEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Mathematics, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Afrikaans, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mMaths, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aAfrikaans, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Remarks, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RemarksL, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Grade, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(108, 108, 108)
                                    .addComponent(gGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(183, 183, 183))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rReset, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(mStudent)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentNumber)
                    .addComponent(sNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(nName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(SubjectModules)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(English)
                    .addComponent(eEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Afrikaans)
                    .addComponent(aAfrikaans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mathematics)
                    .addComponent(mMaths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhysicalSciences)
                    .addComponent(pSciences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(cCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalMarks)
                    .addComponent(tMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Percentage)
                    .addComponent(pPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Grade)
                    .addComponent(gGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rReset)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Remarks)
                            .addComponent(RemarksL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCalculateActionPerformed
        // TODO add your handling code here:
        
        try {
            int stn = Integer.parseInt(sNumber.getText());
            String stuname = nName.getText();
            
            double phy = Double.parseDouble(pSciences.getText());
            double afrik = Double.parseDouble(aAfrikaans.getText());
            double maths = Double.parseDouble(mMaths.getText());
            double eng = Double.parseDouble(eEnglish.getText());
            
            double total = phy + afrik + maths + eng;
            tMarks.setText(" " + total);
            
            double per = (total / 400) * 100;
            pPercentage.setText(" " + per);
            
            String grade;
            
            if (per > 90) {
                grade = "A";
               RemarksL.setText("Amazing");
            }
            else if (per >=80) {
                grade = "B";
                RemarksL.setText("Great");
            }
            else if (per >=70){
                grade = "C";
                RemarksL.setText("Good");
            }
            else if (per >=60){
                grade = "D";
                RemarksL.setText("Okay");
            }
            else if (per >= 50){
                grade = "E";
                RemarksL.setText("Moderate");
            }
            else{
                grade = "Poor";
                RemarksL.setText("You have failed");
            }
            gGrade.setText(" " + grade);
            tMarks.setText(" " + total);
            pPercentage.setText(" " + per);
            
           
        } catch  (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Please enter numeric value");
            
        }
    }//GEN-LAST:event_cCalculateActionPerformed

    private void nNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nNameActionPerformed

    private void rResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rResetActionPerformed
        // TODO add your handling code here:
        pSciences.setText(" ");
        aAfrikaans.setText(" ");
        mMaths.setText(" ");
        eEnglish.setText(" ");
        
        sNumber.setText(" ");
        nName.setText(" ");
        
        gGrade.setText(" ");
        pPercentage.setText(" ");
        tMarks.setText(" ");
        
        
        
    }//GEN-LAST:event_rResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentgrade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Afrikaans;
    private javax.swing.JLabel English;
    private javax.swing.JLabel Grade;
    private javax.swing.JLabel Mathematics;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Percentage;
    private javax.swing.JLabel PhysicalSciences;
    private javax.swing.JLabel Remarks;
    private javax.swing.JTextField RemarksL;
    private javax.swing.JLabel StudentNumber;
    private javax.swing.JLabel SubjectModules;
    private javax.swing.JLabel TotalMarks;
    private javax.swing.JTextField aAfrikaans;
    private javax.swing.JButton cCalculate;
    private javax.swing.JTextField eEnglish;
    private javax.swing.JTextField gGrade;
    private javax.swing.JTextField mMaths;
    private javax.swing.JLabel mStudent;
    private javax.swing.JTextField nName;
    private javax.swing.JTextField pPercentage;
    private javax.swing.JTextField pSciences;
    private javax.swing.JButton rReset;
    private javax.swing.JTextField sNumber;
    private javax.swing.JTextField tMarks;
    // End of variables declaration//GEN-END:variables
}
